openapi: 3.0.4
info:
  title: Instant Messaging API
  description: |
    Spécification d'une API REST pour une messagerie instantanée qui comprend la gestion des utilisateur·rice·s, des conversations et des messages. Cette API est utilisée dans le cadre des modules 194, 195, 322, et 426. 
  version: 1.0.0
  contact:
    name: Jérôme Frossard
    email: jerome.frossard@edufr.ch
    url: 'https://www.epai-ict.ch'
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
servers:
  - url: 'https://message-api.n01.lab.epai-ict.ch'
    description: Production
  - url: 'http://localhost:8080'
    description: Développement
security:
  - BearerAuth: []
tags:
  - name: conversation
    description: Gestion des conversations
  - name: message
    description: Gestion des messages
  - name: participant
    description: Gestion des participant·e·s
  - name: token
    description: Gestion des tokens d'authentification
  - name: user
    description: Gestion des utilisateur·rice·s
paths:
  /tokens:
    post:
      tags:
        - token
      operationId: login
      summary: Crée un token (connexion).
      description: "Renvoie un token d'authentification si le nom d'utilsateur et le mot de passe sont valides."
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRequest'
      responses:
        '200':
          description: Token renvoyé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '406':
          $ref: '#/components/responses/NotAcceptable'
        '415':
          $ref: '#/components/responses/UnsupportedMediaType'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        default:
          $ref: '#/components/responses/InternalServerError'
  /tokens/me:
    delete:
      tags:
        - token
      operationId: logout
      summary: Supprime le token de l'utilisateur·rice connecté·e (déconnexion).
      description: "Supprime le token de l'utilisateur·rice connecté·e (déconnexion). Si le token est invalide ou expiré, la requête ne produit pas d'effet."
      responses:
        '201':
          description: Token supprimé avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: 404
                message: Token supprimé avec succès
        '429':
          $ref: '#/components/responses/TooManyRequests'
        default:
          $ref: '#/components/responses/InternalServerError'
  /users:
    post:
      tags:
        - user
      operationId: create-users
      summary: Crée un compte d'utilisateur·rice.
      description: "Crée un compte d'utilisateur·rice avec un nom d'utilisateur et un mot de passe. Le nom d'utilisateur peut être soit une adresse e-mail, soit un numéro de téléphone au format E.164."
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
            examples:
              exemple1:
                summary: Création du compte avec un email
                value:
                  username: trillian@infinidim.ch
                  password: h2G2-42*
              exemple2:
                summary: Création du compte avec un numéro de téléphone
                value:
                  username: '+41799991234'
                  password: h2G2-42*
      responses:
        '201':
          description: Le compte a été créé avec succès.
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '406':
          $ref: '#/components/responses/NotAcceptable'
        '415':
          $ref: '#/components/responses/UnsupportedMediaType'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        default:
          $ref: '#/components/responses/InternalServerError'
  '/users/{userId}':
    get:
      tags:
        - user
      operationId: get-user
      summary: Récupère les informations d’un·e utilisateur·rice.
      description: "Récupère les informations d'un·e utilisateur·rice à partir de son identifiant."
      parameters:
        - name: userId
          description: Identifiant de l'utilisateur
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 0
            maximum: 9223372036854776000
          example: 1001
      responses:
        '200':
          description: Les détails de l'utilisateur·rice.
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          description: Utilisateur·rice non trouvé·e
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: 404
                message: Utilisateur non trouvé
        '406':
          $ref: '#/components/responses/NotAcceptable'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        default:
          $ref: '#/components/responses/InternalServerError'
    patch:
      tags:
        - user
      operationId: update-user
      summary: Modifie les informations d'un·e utilisateur·rice.
      description: "Modifie les informations d'un·e utilisateur·rice à partir de son identifiant."
      parameters:
        - name: userId
          description: Identifiant de l'utilisateur
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 0
            maximum: 9223372036854776000
          example: 1001
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdate'
            examples:
              changePassword:
                summary: Modification du mot de passe
                value:
                  password: h2G2-42*
              changeUsername:
                summary: Modification du nom d'utilisateur
                value:
                  username: tricia@infinidim.com
      responses:
        '200':
          description: Les informations de l'utilisateur·rice ont été modifiées avec succès.
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          description: Utilisateur·rice non trouvé·e
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: 404
                message: Utilisateur non trouvé
        '406':
          $ref: '#/components/responses/NotAcceptable'
        '415':
          $ref: '#/components/responses/UnsupportedMediaType'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        default:
          $ref: '#/components/responses/InternalServerError'
    delete:
      tags:
        - user
      operationId: delete-user
      summary: Supprime un·e utilisateur·rice.
      description: "Supprime un·e utilisateur·rice à partir de son identifiant. Cette opération est irréversible et entraîne l’anonymisation de tous les messages envoyés par cette personne." 
      parameters:
        - name: userId
          description: Identifiant de l'utilisateur
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 0
            maximum: 9223372036854776000
          example: 1001
      responses:
        '204':
          description: L'utilisateur·rice a été supprimé·e avec succès (suppression logique).
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          description: Utilisateur·rice non trouvé·e
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: 404
                message: Utilisateur non trouvé
        '406':
          $ref: '#/components/responses/NotAcceptable'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        default:
          $ref: '#/components/responses/InternalServerError'
  /conversations:
    get:
      tags:
        - conversation
      operationId: get-conversations
      summary: Récupère les conversations de l'utilisateur·rice.
      description: "Récupère les conversations dans lesquelles l'utilisateur·rice connecté·e est actif·ve."
      parameters:
        - name: page
          description: Numéro de la page (commence à 0).
          in: query
          schema:
            type: integer
            format: int32
            minimum: 0
            maximum: 100
            default: 0
        - name: size
          description: Nombre d'éléments par page (20 par défaut).
          in: query
          schema:
            type: integer
            format: int32
            minimum: 20
            maximum: 100
            default: 20
      responses:
        '200':
          description: Une liste paginée des conversations.
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/ConversationsResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '406':
          $ref: '#/components/responses/NotAcceptable'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        default:
          $ref: '#/components/responses/InternalServerError'
    post:
      tags:
        - conversation
      operationId: create-conversation
      summary: Crée une nouvelle conversation.
      description: "Crée une nouvelle conversation avec un ou plusieurs participant·e·s. Le nom d'utilisateur peut être soit une adresse e-mail, soit un numéro de téléphone au format E.164."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConversationCreate'
            examples:
              singleParticipantUsername:
                summary: Avec un·e seul·e participant·e (username)
                value:
                  username: trevize@example.com
              singleParticipantId:
                summary: Avec un·e seul·e participant·e (id)
                value:
                  userId: 14
              multipleParticipantsId:
                summary: Avec plusieurs participant·e·s
                value:
                  participants:
                    - userId: 14
                      role: MEMBER
                      status: ACTIVE
                    - username: siona@example.com
      responses:
        '201':
          description: La conversation a été créée avec succès.
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/ConversationsResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '406':
          $ref: '#/components/responses/NotAcceptable'
        '415':
          $ref: '#/components/responses/UnsupportedMediaType'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        default:
          $ref: '#/components/responses/InternalServerError'
  '/conversations/{conversationId}':
    get:
      tags:
        - conversation
      operationId: get-conversation
      summary: Récupère les détails d'une conversation.
      description: "Récupère les détails d'une conversation à partir de son identifiant."
      parameters:
        - name: conversationId
          description: Identifiant de la conversation.
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 0
            maximum: 9223372036854776000
          example: 4005
      responses:
        '200':
          description: Les détails de la conversation.
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/ConversationResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          description: Conversation non trouvée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: 404
                message: Conversation non trouvée
        '406':
          $ref: '#/components/responses/NotAcceptable'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        default:
          $ref: '#/components/responses/InternalServerError'
  '/conversations/{conversationId}/participants':
    get:
      tags:
        - participant
      operationId: get-participants
      summary: Récupèrer la liste des participant·e·s d'une conversation.
      description: "Récupère la liste des participant·e·s d'une conversation à partir de son identifiant."
      parameters:
        - name: conversationId
          description: Identifiant de la conversation.
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 0
            maximum: 9223372036854776000
          example: 4005
      responses:
        '200':
          description: La liste des participant·e·s de la conversation.
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/ParticipantsResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          description: Conversation non trouvée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: 404
                message: Conversation non trouvée
        '406':
          $ref: '#/components/responses/NotAcceptable'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        default:
          $ref: '#/components/responses/InternalServerError'
  '/conversations/{conversationId}/participants/{participantId}':
    patch:
      tags:
        - participant
      operationId: update-participant
      summary: Modifie le rôle ou le statut d'un·e participant·e.
      description: >
        Modifie le rôle ou le statut d'un·e participant·e à partir de son identifiant.

        * Si la conversation est une conversation de groupe, le ou la propriétaire de la conversation peut bloquer un·e participant·e non propriétaire ou lui attribuer le rôle de propriétaire.
        
        * Si la conversation est une conversation privée, un·e participant·e peut changer son propre status d'actif à inactif. Cette opération est irréversible et entraîne la suppression logique de tous les messages de la conversation pour cette personne.
      security:
        - BearerAuth: []
      parameters:
        - name: conversationId
          description: Identifiant de la conversation.
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 0
            maximum: 9223372036854776000
          example: 4005
        - name: participantId
          description: Identifiant du participant.
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 0
            maximum: 9223372036854776000
          example: 1001
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParticipantUpdate'
      responses:
        '200':
          description: Le rôle ou le statut de lea participant·e a été modifié avec succès.
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/ParticipantResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          description: Participant·e non trouvé·e
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: 404
                message: Participant·e non trouvé·e
        '406':
          $ref: '#/components/responses/NotAcceptable'
        '415':
          $ref: '#/components/responses/UnsupportedMediaType'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        default:
          $ref: '#/components/responses/InternalServerError'
  '/conversations/{conversationId}/messages':
    get:
      tags:
        - message
      operationId: get-messages
      summary: Récupère les messages d'une conversation
      description: "Récupère les messages d'une conversation à partir de son identifiant."
      parameters:
        - name: conversationId
          description: Identifiant de la conversation.
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 0
            maximum: 9223372036854776000
          example: 4005
        - name: page
          description: Numéro de la page (commence à 0).
          in: query
          schema:
            type: integer
            format: int32
            minimum: 0
            maximum: 100
            default: 0
        - name: size
          description: Nombre d'éléments par page (20 par défaut).
          in: query
          schema:
            type: integer
            format: int32
            minimum: 20
            maximum: 100
            default: 20
      responses:
        '200':
          description: La liste paginée des messages de la conversation.
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/MessagesResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          description: Conversation non trouvée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: 404
                message: Conversation non trouvée
        '406':
          $ref: '#/components/responses/NotAcceptable'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        default:
          $ref: '#/components/responses/InternalServerError'
    post:
      tags:
        - message
      operationId: create-message
      summary: Ajoute un message à la conversation
      description: "Ajoute un message à la conversation à partir de son identifiant."
      parameters:
        - name: conversationId
          description: Identifiant de la conversation.
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 0
            maximum: 9223372036854776000
          example: 4005
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageCreate'
      responses:
        '201':
          description: Le message a été envoyé avec succès.
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          description: Conversation non trouvée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: 404
                message: Conversation non trouvée
        '406':
          $ref: '#/components/responses/NotAcceptable'
        '415':
          $ref: '#/components/responses/UnsupportedMediaType'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        default:
          $ref: '#/components/responses/InternalServerError'
  '/conversations/{conversationId}/messages/{messageId}':
    patch:
      tags:
        - message
      operationId: update-message-status
      summary: Modifie le statut du message pour un participant
      description: >
        Modifie le statut d’un message pour l’utilisateur·rice connecté·e.

        * Si le message est lu, le champ `readAt` est mis à jour avec la date et l’heure de lecture.

        * Si le message doit être supprimé pour l'utilisateur·rice, le champ `deleted` est mis à `true`. Cette opération est irréversible et entraîne la suppression logique du message pour cette personne uniquement.
      parameters:
        - name: conversationId
          description: Identifiant de la conversation.
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 0
            maximum: 9223372036854776000
          example: 4005
        - name: messageId
          description: Identifiant du message.
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 0
            maximum: 9223372036854776000
          example: 6001
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageStatusUpdate'
      responses:
        '200':
          description: Le statut du message a été modifié avec succès.
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
              example:
                id: 6001
                senderId: 1001
                body: J'aurai un peu de retard. Commencez sans moi
                sentAt: '2025-04-24T15:00:00Z'
                status:
                  - userId: 1002
                    readAt: '2025-04-24T15:03:00Z'
                    deleted: false
                  - userId: 1003
                    readAt: null
                    deleted: false
                _links:
                  self:
                    href: http://localhost:8080/conversations/4005/message/6001
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          description: Conversation ou message non trouvée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: 404
                message: Conversation ou message non trouvée
        '406':
          $ref: '#/components/responses/NotAcceptable'
        '415':
          $ref: '#/components/responses/UnsupportedMediaType'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        default:
          $ref: '#/components/responses/InternalServerError'
    
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
          maxLength: 255
          pattern: '^.{1,255}$'
      additionalProperties: false
    UuidType:
      type: string
      format: uuid
      maxLength: 36
      pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
    UriType:
      type: string
      format: uri
      maxLength: 2048
      pattern: '^https?:\/\/[a-zA-Z0-9.-]+(:[0-9]+)?(\/[a-zA-Z0-9._~:/?#\[\]@!$&''()*+,;=%-]*)?$'
    EmailType:
      type: string
      format: email
      maxLength: 254
      pattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
    PhoneNumberType:
      description: Numéro de téléphone au format E.164.
      type: string
      maxLength: 16
      pattern: '^\+?[1-9]\d{1,14}$'
    UserNameType:
      oneOf:
        - $ref: '#/components/schemas/EmailType'
        - $ref: '#/components/schemas/PhoneNumberType'
      additionalProperties: true
    HalLinks:
      type: object
      properties:
        self:
          type: object
          properties:
            href:
              $ref: '#/components/schemas/UriType'
          additionalProperties: false
      additionalProperties: true
    HalCollectionLinks:
      type: object
      properties:
        self:
          type: object
          properties:
            href:
              $ref: '#/components/schemas/UriType'
          additionalProperties: false
        first:
          type: object
          properties:
            href:
              $ref: '#/components/schemas/UriType'
          additionalProperties: false
        last:
          type: object
          properties:
            href:
              $ref: '#/components/schemas/UriType'
          additionalProperties: false
        next:
          type: object
          properties:
            href:
              $ref: '#/components/schemas/UriType'
          additionalProperties: false
        prev:
          type: object
          properties:
            href:
              $ref: '#/components/schemas/UriType'
          additionalProperties: false
      additionalProperties: false
    PageMetadata:
      type: object
      properties:
        size:
          type: integer
          format: int32
        totalElements:
          type: integer
          format: int32
        totalPages:
          type: integer
          format: int32
        number:
          type: integer
          format: int32
      additionalProperties: false
      example:
        size: 20
        totalElements: 1
        totalPages: 1
        number: 0
    UserCreate:
      type: object
      required:
        - username
        - password
      properties:
        username:
          $ref: '#/components/schemas/UserNameType'
        password:
          type: string
          format: password
          minLength: 8
          maxLength: 128
          pattern: '^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^a-zA-Z\d]).{8,}$'
      additionalProperties: false
    UserUpdate:
      type: object
      properties:
        username:
          $ref: '#/components/schemas/UserNameType'
        password:
          type: string
          format: password
          minLength: 8
          maxLength: 128
          pattern: '^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^a-zA-Z\d]).{8,}$'
      additionalProperties: false
    UserResponse:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        username:
          $ref: '#/components/schemas/UserNameType'
        _links:
          $ref: '#/components/schemas/HalLinks'
      additionalProperties: false
      example:
        userId: 1001
        username: trillian@infinidim.com
        _links:
          self:
            href: http://localhost:8080/users/1001
    TokenRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          $ref: '#/components/schemas/UserNameType'
        password:
          type: string
          format: password
          minLength: 8
          maxLength: 128
          pattern: '^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^a-zA-Z\d]).{8,}$'
      additionalProperties: false
      example:
        username: trillian@infinidim.com
        password: h2G2-42*
    TokenResponse:
      type: object
      properties:
        token:
          $ref: '#/components/schemas/UuidType'
      additionalProperties: false
      example:
        token: 550e8400-e29b-41d4-a716-446655440000
    ParticipantRoleType:
      type: string
      enum:
        - MEMBER
        - OWNER
    ParticipantStatusType:
      type: string
      enum:
        - ACTIVE
        - INACTIVE
        - BLOCKED
    ParticipantCreateFromUserId:
      type: object
      required:
        - userId
      properties:
        userId:
          type: integer
          format: int64
          minimum: 0
          maximum: 9223372036854776000
        role:
          $ref: '#/components/schemas/ParticipantRoleType'
        status:
          $ref: '#/components/schemas/ParticipantStatusType'
      additionalProperties: false
      example:
        userId: 1001
        role: OWNER
        status: ACTIVE
    ParticipantCreateFromUsername:
      type: object
      required:
        - username
      properties:
        username:
          $ref: '#/components/schemas/UserNameType'
        role:
          $ref: '#/components/schemas/ParticipantRoleType'
        status:
          $ref: '#/components/schemas/ParticipantStatusType'
      additionalProperties: false
      example:
        username: trillian@infinidim.ch
        role: OWNER
        status: ACTIVE
    ParticipantCreate:
      oneOf:
        - $ref: '#/components/schemas/ParticipantCreateFromUserId'
        - $ref: '#/components/schemas/ParticipantCreateFromUsername'
      additionalProperties: true
    ParticipantUpdate:
      type: object
      properties:
        role:
          $ref: '#/components/schemas/ParticipantRoleType'
        status:
          $ref: '#/components/schemas/ParticipantStatusType'
      additionalProperties: false
      example:
        role: MEMBER
        status: ACTIVE
    ParticipantResponse:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        username:
          $ref: '#/components/schemas/UserNameType'
        role:
          $ref: '#/components/schemas/ParticipantRoleType'
        status:
          $ref: '#/components/schemas/ParticipantStatusType'
        _links:
          $ref: '#/components/schemas/HalLinks'
      additionalProperties: false
      example:
        userId: 1001
        username: trillian@infinidim.ch
        role: MEMBER
        status: ACTIVE
        _links:
          self:
            href: http://localhost:8080/conversations/4005/participants/1001
    ParticipantsResponse:
      type: object
      properties:
        _embedded:
          type: object
          properties:
            participants:
              type: array
              maxItems: 15
              items:
                $ref: '#/components/schemas/ParticipantResponse'
          additionalProperties: false
        _links:
          $ref: '#/components/schemas/HalLinks'
      additionalProperties: false
      example:
        _embedded:
          participants:
            - userId: 1001
              username: trillian@infinidim.ch
              role: MEMBER
              status: ACTIVE
              _links:
                self:
                  href: http://localhost:8080/conversations/4005/participants/1001
            - userId: 1002
              username: "+41799991234"
              role: MEMBER
              status: ACTIVE
              _links:
                self:
                  href: http://localhost:8080/conversations/4005/participants/1002
        _links:
          self:
            href: http://localhost:8080/conversations/4005/participants
    ConversationCreateFromSingleUserId:
        type: object
        required:
          - userId
        properties:
          userId:
            type: integer
            format: int64
            minimum: 0
            maximum: 9223372036854776000
        additionalProperties: false
        example:
          userId: 1002
    ConversationCreateFromSingleUsername:
        type: object
        required:
          - username
        properties:
          username:
            $ref: '#/components/schemas/UserNameType'
        additionalProperties: false
        example:
          username: trillian@infinidim.ch
    ConversationCreateMultiple:
      type: object
      properties:
        participants:
          type: array
          items:
            $ref: '#/components/schemas/ParticipantCreate'
          minItems: 1
          maxItems: 100
      additionalProperties: false
      example:
        participants:
          - userId: 14
            role: MEMBER
            status: ACTIVE
          - username: siona@example.com
    ConversationCreate:
      oneOf:
        - $ref: '#/components/schemas/ConversationCreateFromSingleUserId'
        - $ref: '#/components/schemas/ConversationCreateFromSingleUsername'
        - $ref: '#/components/schemas/ConversationCreateMultiple'
      additionalProperties: true
    ConversationResponse:
      allOf:
        - type: object
          properties:
            id:
              type: integer
              format: int64
            isGroup:
              type: boolean
              default: false
            _links:
              allOf:
                - $ref: '#/components/schemas/HalLinks'
                - type: object
                  properties:
                    messages:
                      type: object
                      properties:
                        href:
                          $ref: '#/components/schemas/UriType'
                  additionalProperties: true
              additionalProperties: true
        - $ref: '#/components/schemas/ParticipantsResponse'
      additionalProperties: true
      example:
        id: 4005
        isGroup: false
        _embedded:
          participants:
            - userId: 1001
              username: trillian@infinidim.ch
              role: MEMBER
              status: ACTIVE
              _links:
                self:
                  href: /conversations/4005/participants/1001
            - userId: 1002
              username: 41799991234
              role: MEMBER
              status: ACTIVE
              _links:
                self:
                  href: /conversations/4005/participants/1002
        _links:
          self:
            href: /conversations/4005
          messages:
            href: /conversations/4005/messages
          participants:
            href: /conversations/4005/participants
    ConversationsResponse:
      type: object
      properties:
        _embedded:
          type: object
          properties:
            conversations:
              type: array
              maxItems: 100
              items:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                  _embedded:
                    type: object
                    properties:
                      participants:
                        type: array
                        maxItems: 100
                        items:
                          $ref: '#/components/schemas/ParticipantResponse'
                    additionalProperties: false
                  _links:
                    allOf:
                      - $ref: '#/components/schemas/HalLinks'
                      - type: object
                        properties:
                          messages:
                            type: object
                            properties:
                              href:
                                $ref: '#/components/schemas/UriType'
                        additionalProperties: true
                    additionalProperties: true
                additionalProperties: true
        page:
          $ref: '#/components/schemas/PageMetadata'
        _links:
          $ref: '#/components/schemas/HalCollectionLinks'
      additionalProperties: false
      example:
        _embedded:
          conversations:
            - id: 4005
              isGroup: false
              _links:
                self:
                  href: http://localhost:8080/conversations/4005
                messages:
                  href: http://localhost:8080/conversations/4005/messages
              _embedded:
                participants:
                  - userId: 1001
                    username: trillian@infinidim.ch
                    role: MEMBER
                    status: ACTIVE
                    _links:
                      self:
                        href: http://localhost:8080/conversations/4005/participants/1001
                  - userId: 1002
                    username: "+41799991234"
                    role: MEMBER
                    status: ACTIVE
                    _links:
                      self:
                        href: http://localhost:8080/conversations/4005/participants/1002
        page:
          size: 20
          totalElements: 1
          totalPages: 1
          number: 0
        _links:
          self:
            href: http://localhost:8080/conversations
          first:
            href: http://localhost:8080/conversations?page=0
          next:
            href: http://localhost:8080/conversations?page=1
          last:
            href: http://localhost:8080/conversations?page=10
    MessageCreate:
      type: object
      required:
        - body
      properties:
        body:
          type: string
          maxLength: 2000
          pattern: '^.{1,2000}$'
      additionalProperties: false
      example:
        body: J'aurai un peu de retard. Commencez sans moi.
    MessageResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        senderId:
          type: integer
          format: int64
        body:
          type: string
          maxLength: 2000
        sentAt:
          type: string
          format: date-time
        status:
          type: array
          maxItems: 15
          items:
            type: object
            properties:
              userId:
                type: integer
                format: int64
              readAt:
                type: string
                nullable: true
                format: date-time
              deleted:
                type: boolean
            additionalProperties: false
        _links:
          $ref: '#/components/schemas/HalLinks'
      additionalProperties: false
      example:
        id: 6001
        senderId: 1001
        body: J'aurai un peu de retard. Commencez sans moi
        sentAt: '2025-04-24T15:00:00Z'
        status:
          - userId: 1002
            readAt: null
            deleted: false
          - userId: 1003
            readAt: null
            deleted: false
        _links:
          self:
            href: http://localhost:8080/conversations/4005/message/6001
    MessagesResponse:
      type: object
      properties:
        _links:
          $ref: '#/components/schemas/HalLinks'
        _embedded:
          type: object
          properties:
            messages:
              type: array
              maxItems: 100
              items:
                $ref: '#/components/schemas/MessageResponse'
          additionalProperties: false
        page:
          $ref: '#/components/schemas/PageMetadata'
      additionalProperties: false
      example:
        _embedded:
          messages:
            - id: 6001
              senderId: 1001
              body: J'aurai un peu de retard. Commencez sans moi
              sentAt: '2025-04-24T15:00:00Z'
              status:
                - userId: 1002
                  readAt: '2025-04-24T15:01:00Z'
                  deleted: false
                - userId: 1003
                  readAt: null
                  deleted: false
              _links:
                self:
                  href: http://localhost:8080/conversations/4005/messages/6001
        _links:
          self: 
            href: http://localhost:8080/conversations/4005/messages
        page:
          size: 20
          totalElements: 1
          totalPages: 1
          number: 0
    MessageStatusUpdate:
      oneOf: 
        - type: object
          required:
            - readAt
          properties:
            readAt:
              type: string
              format: date-time
          additionalProperties: false
          example:
            readAt: '2025-04-24T15:03:00Z'
        - type: object
          required:
            - deleted
          properties:
            deleted:
              type: boolean
          additionalProperties: false
          example:
            deleted: true
      additionalProperties: false

  responses:
    BadRequest:
      description: Requête invalide
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            code: 400
            message: Requête invalide
    Unauthorized:
      description: Non autorisé
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            code: 401
            message: Identifiants de connexion non valides.
    Forbidden:
      description: Accès refusé
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            code: 403
            message: Accès refusé
    NotAcceptable:
      description: Not Acceptable
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            code: 406
            message: Not Acceptable
    UnsupportedMediaType:
      description: Unsupported Media Type
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            code: 415
            message: Unsupported Media Type
    TooManyRequests:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            code: 429
            message: Too Many Requests
    InternalServerError:
      description: Erreur interne du serveur
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            code: 500
            message: Erreur interne du serveur
